/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Comp.Dialog;

/**
 *
 * @author quang
 */
public class DialogQuestion extends javax.swing.JDialog {

    /**
     * Creates new form DialogQuestion
     */
    public DialogQuestion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBackground1 = new GUI.Comp.Swing.PanelBackground();
        panelBackground2 = new GUI.Comp.Swing.PanelBackground();
        panelBackground3 = new GUI.Comp.Swing.PanelBackground();
        panelBackground4 = new GUI.Comp.Swing.PanelBackground();
        panelBackground5 = new GUI.Comp.Swing.PanelBackground();
        pnCenter = new GUI.Comp.Swing.PanelBackground();
        pnTop = new GUI.Comp.Swing.PanelBackground();
        pnQuestion = new GUI.Comp.Swing.PanelBackground();
        jLabel1 = new javax.swing.JLabel();
        panelBackground6 = new GUI.Comp.Swing.PanelBackground();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelBackground10 = new GUI.Comp.Swing.PanelBackground();
        panelBackground11 = new GUI.Comp.Swing.PanelBackground();
        pnAnwser = new GUI.Comp.Swing.PanelBackground();
        jLabel2 = new javax.swing.JLabel();
        panelBackground7 = new GUI.Comp.Swing.PanelBackground();
        panelBackground8 = new GUI.Comp.Swing.PanelBackground();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        panelBackground12 = new GUI.Comp.Swing.PanelBackground();
        jButton2 = new javax.swing.JButton();
        panelBackground9 = new GUI.Comp.Swing.PanelBackground();
        jButton1 = new javax.swing.JButton();
        panelBackground16 = new GUI.Comp.Swing.PanelBackground();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        panelBackground17 = new GUI.Comp.Swing.PanelBackground();
        jButton5 = new javax.swing.JButton();
        panelBackground18 = new GUI.Comp.Swing.PanelBackground();
        jButton6 = new javax.swing.JButton();
        panelBackground19 = new GUI.Comp.Swing.PanelBackground();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        panelBackground20 = new GUI.Comp.Swing.PanelBackground();
        jButton7 = new javax.swing.JButton();
        panelBackground21 = new GUI.Comp.Swing.PanelBackground();
        jButton8 = new javax.swing.JButton();
        panelBackground22 = new GUI.Comp.Swing.PanelBackground();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        panelBackground23 = new GUI.Comp.Swing.PanelBackground();
        jButton9 = new javax.swing.JButton();
        panelBackground24 = new GUI.Comp.Swing.PanelBackground();
        jButton10 = new javax.swing.JButton();
        pnBottom = new GUI.Comp.Swing.PanelBackground();
        line = new GUI.Comp.Swing.PanelBackground();
        panelBackground13 = new GUI.Comp.Swing.PanelBackground();
        jLabel3 = new javax.swing.JLabel();
        panelBackground27 = new GUI.Comp.Swing.PanelBackground();
        panelBackground28 = new GUI.Comp.Swing.PanelBackground();
        jLabel6 = new javax.swing.JLabel();
        panelBackground29 = new GUI.Comp.Swing.PanelBackground();
        jComboBox3 = new javax.swing.JComboBox<>();
        panelBackground30 = new GUI.Comp.Swing.PanelBackground();
        jLabel7 = new javax.swing.JLabel();
        panelBackground31 = new GUI.Comp.Swing.PanelBackground();
        jComboBox4 = new javax.swing.JComboBox<>();
        panelBackground32 = new GUI.Comp.Swing.PanelBackground();
        jButton4 = new javax.swing.JButton();
        panelBackground33 = new GUI.Comp.Swing.PanelBackground();
        panelBackground34 = new GUI.Comp.Swing.PanelBackground();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground1.setLayout(new java.awt.BorderLayout());

        panelBackground2.setMinimumSize(new java.awt.Dimension(100, 20));
        panelBackground2.setPreferredSize(new java.awt.Dimension(995, 20));

        javax.swing.GroupLayout panelBackground2Layout = new javax.swing.GroupLayout(panelBackground2);
        panelBackground2.setLayout(panelBackground2Layout);
        panelBackground2Layout.setHorizontalGroup(
            panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        panelBackground2Layout.setVerticalGroup(
            panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelBackground1.add(panelBackground2, java.awt.BorderLayout.PAGE_START);

        panelBackground3.setPreferredSize(new java.awt.Dimension(20, 616));

        javax.swing.GroupLayout panelBackground3Layout = new javax.swing.GroupLayout(panelBackground3);
        panelBackground3.setLayout(panelBackground3Layout);
        panelBackground3Layout.setHorizontalGroup(
            panelBackground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelBackground3Layout.setVerticalGroup(
            panelBackground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelBackground1.add(panelBackground3, java.awt.BorderLayout.LINE_START);

        panelBackground4.setPreferredSize(new java.awt.Dimension(20, 616));

        javax.swing.GroupLayout panelBackground4Layout = new javax.swing.GroupLayout(panelBackground4);
        panelBackground4.setLayout(panelBackground4Layout);
        panelBackground4Layout.setHorizontalGroup(
            panelBackground4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelBackground4Layout.setVerticalGroup(
            panelBackground4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelBackground1.add(panelBackground4, java.awt.BorderLayout.LINE_END);

        panelBackground5.setMinimumSize(new java.awt.Dimension(100, 20));
        panelBackground5.setPreferredSize(new java.awt.Dimension(995, 20));

        javax.swing.GroupLayout panelBackground5Layout = new javax.swing.GroupLayout(panelBackground5);
        panelBackground5.setLayout(panelBackground5Layout);
        panelBackground5Layout.setHorizontalGroup(
            panelBackground5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        panelBackground5Layout.setVerticalGroup(
            panelBackground5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelBackground1.add(panelBackground5, java.awt.BorderLayout.PAGE_END);

        pnCenter.setLayout(new java.awt.BorderLayout(0, 15));

        pnTop.setLayout(new java.awt.GridLayout(2, 1, 0, 15));

        pnQuestion.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel1.setText("Câu hỏi");
        pnQuestion.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        panelBackground6.setLayout(new javax.swing.BoxLayout(panelBackground6, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 96));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelBackground6.add(jScrollPane1);

        panelBackground10.setPreferredSize(new java.awt.Dimension(30, 241));

        javax.swing.GroupLayout panelBackground10Layout = new javax.swing.GroupLayout(panelBackground10);
        panelBackground10.setLayout(panelBackground10Layout);
        panelBackground10Layout.setHorizontalGroup(
            panelBackground10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelBackground10Layout.setVerticalGroup(
            panelBackground10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        panelBackground6.add(panelBackground10);

        panelBackground11.setBackground(new java.awt.Color(255, 153, 0));
        panelBackground11.setPreferredSize(new java.awt.Dimension(350, 241));

        javax.swing.GroupLayout panelBackground11Layout = new javax.swing.GroupLayout(panelBackground11);
        panelBackground11.setLayout(panelBackground11Layout);
        panelBackground11Layout.setHorizontalGroup(
            panelBackground11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelBackground11Layout.setVerticalGroup(
            panelBackground11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        panelBackground6.add(panelBackground11);

        pnQuestion.add(panelBackground6, java.awt.BorderLayout.CENTER);

        pnTop.add(pnQuestion);

        pnAnwser.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel2.setText("Câu trả lời");
        pnAnwser.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        panelBackground7.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        panelBackground8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jRadioButton1.setPreferredSize(new java.awt.Dimension(25, 30));
        panelBackground8.add(jRadioButton1);

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.setMinimumSize(new java.awt.Dimension(64, 30));
        jTextField1.setPreferredSize(new java.awt.Dimension(700, 30));
        panelBackground8.add(jTextField1);

        panelBackground12.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground12Layout = new javax.swing.GroupLayout(panelBackground12);
        panelBackground12.setLayout(panelBackground12Layout);
        panelBackground12Layout.setHorizontalGroup(
            panelBackground12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground12Layout.setVerticalGroup(
            panelBackground12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground8.add(panelBackground12);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/image.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        panelBackground8.add(jButton2);

        panelBackground9.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground9Layout = new javax.swing.GroupLayout(panelBackground9);
        panelBackground9.setLayout(panelBackground9Layout);
        panelBackground9Layout.setHorizontalGroup(
            panelBackground9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground9Layout.setVerticalGroup(
            panelBackground9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground8.add(panelBackground9);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/delete.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        panelBackground8.add(jButton1);

        panelBackground7.add(panelBackground8);

        panelBackground16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jRadioButton3.setPreferredSize(new java.awt.Dimension(25, 30));
        panelBackground16.add(jRadioButton3);

        jTextField3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextField3.setText("jTextField1");
        jTextField3.setMinimumSize(new java.awt.Dimension(64, 30));
        jTextField3.setPreferredSize(new java.awt.Dimension(700, 30));
        panelBackground16.add(jTextField3);

        panelBackground17.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground17Layout = new javax.swing.GroupLayout(panelBackground17);
        panelBackground17.setLayout(panelBackground17Layout);
        panelBackground17Layout.setHorizontalGroup(
            panelBackground17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground17Layout.setVerticalGroup(
            panelBackground17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground16.add(panelBackground17);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/image.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setPreferredSize(new java.awt.Dimension(30, 30));
        panelBackground16.add(jButton5);

        panelBackground18.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground18Layout = new javax.swing.GroupLayout(panelBackground18);
        panelBackground18.setLayout(panelBackground18Layout);
        panelBackground18Layout.setHorizontalGroup(
            panelBackground18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground18Layout.setVerticalGroup(
            panelBackground18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground16.add(panelBackground18);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/delete.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(30, 30));
        panelBackground16.add(jButton6);

        panelBackground7.add(panelBackground16);

        panelBackground19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jRadioButton4.setPreferredSize(new java.awt.Dimension(25, 30));
        panelBackground19.add(jRadioButton4);

        jTextField4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextField4.setText("jTextField1");
        jTextField4.setMinimumSize(new java.awt.Dimension(64, 30));
        jTextField4.setPreferredSize(new java.awt.Dimension(700, 30));
        panelBackground19.add(jTextField4);

        panelBackground20.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground20Layout = new javax.swing.GroupLayout(panelBackground20);
        panelBackground20.setLayout(panelBackground20Layout);
        panelBackground20Layout.setHorizontalGroup(
            panelBackground20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground20Layout.setVerticalGroup(
            panelBackground20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground19.add(panelBackground20);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/image.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setPreferredSize(new java.awt.Dimension(30, 30));
        panelBackground19.add(jButton7);

        panelBackground21.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground21Layout = new javax.swing.GroupLayout(panelBackground21);
        panelBackground21.setLayout(panelBackground21Layout);
        panelBackground21Layout.setHorizontalGroup(
            panelBackground21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground21Layout.setVerticalGroup(
            panelBackground21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground19.add(panelBackground21);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/delete.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setPreferredSize(new java.awt.Dimension(30, 30));
        panelBackground19.add(jButton8);

        panelBackground7.add(panelBackground19);

        panelBackground22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jRadioButton5.setPreferredSize(new java.awt.Dimension(25, 30));
        panelBackground22.add(jRadioButton5);

        jTextField5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextField5.setText("jTextField1");
        jTextField5.setMinimumSize(new java.awt.Dimension(64, 30));
        jTextField5.setPreferredSize(new java.awt.Dimension(700, 30));
        panelBackground22.add(jTextField5);

        panelBackground23.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground23Layout = new javax.swing.GroupLayout(panelBackground23);
        panelBackground23.setLayout(panelBackground23Layout);
        panelBackground23Layout.setHorizontalGroup(
            panelBackground23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground23Layout.setVerticalGroup(
            panelBackground23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground22.add(panelBackground23);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/image.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setPreferredSize(new java.awt.Dimension(30, 30));
        panelBackground22.add(jButton9);

        panelBackground24.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground24Layout = new javax.swing.GroupLayout(panelBackground24);
        panelBackground24.setLayout(panelBackground24Layout);
        panelBackground24Layout.setHorizontalGroup(
            panelBackground24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground24Layout.setVerticalGroup(
            panelBackground24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground22.add(panelBackground24);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/delete.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setPreferredSize(new java.awt.Dimension(30, 30));
        panelBackground22.add(jButton10);

        panelBackground7.add(panelBackground22);

        pnAnwser.add(panelBackground7, java.awt.BorderLayout.CENTER);

        pnTop.add(pnAnwser);

        pnCenter.add(pnTop, java.awt.BorderLayout.CENTER);

        pnBottom.setForeground(new java.awt.Color(204, 204, 204));
        pnBottom.setPreferredSize(new java.awt.Dimension(832, 100));
        pnBottom.setLayout(new java.awt.BorderLayout());

        line.setBackground(new java.awt.Color(204, 204, 204));
        line.setPreferredSize(new java.awt.Dimension(832, 1));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnBottom.add(line, java.awt.BorderLayout.PAGE_START);

        panelBackground13.setLayout(new java.awt.GridLayout(2, 1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setText("Cài đặt");
        panelBackground13.add(jLabel3);

        panelBackground27.setLayout(new java.awt.BorderLayout());

        panelBackground28.setPreferredSize(new java.awt.Dimension(500, 49));
        panelBackground28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setText("Chủ đề");
        panelBackground28.add(jLabel6);

        panelBackground29.setPreferredSize(new java.awt.Dimension(10, 30));

        javax.swing.GroupLayout panelBackground29Layout = new javax.swing.GroupLayout(panelBackground29);
        panelBackground29.setLayout(panelBackground29Layout);
        panelBackground29Layout.setHorizontalGroup(
            panelBackground29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelBackground29Layout.setVerticalGroup(
            panelBackground29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground28.add(panelBackground29);

        jComboBox3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setPreferredSize(new java.awt.Dimension(150, 30));
        panelBackground28.add(jComboBox3);

        panelBackground30.setPreferredSize(new java.awt.Dimension(10, 30));

        javax.swing.GroupLayout panelBackground30Layout = new javax.swing.GroupLayout(panelBackground30);
        panelBackground30.setLayout(panelBackground30Layout);
        panelBackground30Layout.setHorizontalGroup(
            panelBackground30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelBackground30Layout.setVerticalGroup(
            panelBackground30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground28.add(panelBackground30);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setText("Độ khó");
        panelBackground28.add(jLabel7);

        panelBackground31.setPreferredSize(new java.awt.Dimension(10, 30));

        javax.swing.GroupLayout panelBackground31Layout = new javax.swing.GroupLayout(panelBackground31);
        panelBackground31.setLayout(panelBackground31Layout);
        panelBackground31Layout.setHorizontalGroup(
            panelBackground31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelBackground31Layout.setVerticalGroup(
            panelBackground31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground28.add(panelBackground31);

        jComboBox4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setPreferredSize(new java.awt.Dimension(150, 30));
        panelBackground28.add(jComboBox4);

        panelBackground27.add(panelBackground28, java.awt.BorderLayout.LINE_START);

        panelBackground32.setPreferredSize(new java.awt.Dimension(75, 49));
        panelBackground32.setLayout(new java.awt.BorderLayout());

        jButton4.setBackground(new java.awt.Color(225, 99, 73));
        jButton4.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Lưu");
        panelBackground32.add(jButton4, java.awt.BorderLayout.CENTER);

        panelBackground33.setPreferredSize(new java.awt.Dimension(100, 5));

        javax.swing.GroupLayout panelBackground33Layout = new javax.swing.GroupLayout(panelBackground33);
        panelBackground33.setLayout(panelBackground33Layout);
        panelBackground33Layout.setHorizontalGroup(
            panelBackground33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        panelBackground33Layout.setVerticalGroup(
            panelBackground33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        panelBackground32.add(panelBackground33, java.awt.BorderLayout.PAGE_START);

        panelBackground34.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout panelBackground34Layout = new javax.swing.GroupLayout(panelBackground34);
        panelBackground34.setLayout(panelBackground34Layout);
        panelBackground34Layout.setHorizontalGroup(
            panelBackground34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        panelBackground34Layout.setVerticalGroup(
            panelBackground34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelBackground32.add(panelBackground34, java.awt.BorderLayout.PAGE_END);

        panelBackground27.add(panelBackground32, java.awt.BorderLayout.LINE_END);

        panelBackground13.add(panelBackground27);

        pnBottom.add(panelBackground13, java.awt.BorderLayout.CENTER);

        pnCenter.add(pnBottom, java.awt.BorderLayout.PAGE_END);

        panelBackground1.add(pnCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogQuestion dialog = new DialogQuestion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private GUI.Comp.Swing.PanelBackground line;
    private GUI.Comp.Swing.PanelBackground panelBackground1;
    private GUI.Comp.Swing.PanelBackground panelBackground10;
    private GUI.Comp.Swing.PanelBackground panelBackground11;
    private GUI.Comp.Swing.PanelBackground panelBackground12;
    private GUI.Comp.Swing.PanelBackground panelBackground13;
    private GUI.Comp.Swing.PanelBackground panelBackground16;
    private GUI.Comp.Swing.PanelBackground panelBackground17;
    private GUI.Comp.Swing.PanelBackground panelBackground18;
    private GUI.Comp.Swing.PanelBackground panelBackground19;
    private GUI.Comp.Swing.PanelBackground panelBackground2;
    private GUI.Comp.Swing.PanelBackground panelBackground20;
    private GUI.Comp.Swing.PanelBackground panelBackground21;
    private GUI.Comp.Swing.PanelBackground panelBackground22;
    private GUI.Comp.Swing.PanelBackground panelBackground23;
    private GUI.Comp.Swing.PanelBackground panelBackground24;
    private GUI.Comp.Swing.PanelBackground panelBackground27;
    private GUI.Comp.Swing.PanelBackground panelBackground28;
    private GUI.Comp.Swing.PanelBackground panelBackground29;
    private GUI.Comp.Swing.PanelBackground panelBackground3;
    private GUI.Comp.Swing.PanelBackground panelBackground30;
    private GUI.Comp.Swing.PanelBackground panelBackground31;
    private GUI.Comp.Swing.PanelBackground panelBackground32;
    private GUI.Comp.Swing.PanelBackground panelBackground33;
    private GUI.Comp.Swing.PanelBackground panelBackground34;
    private GUI.Comp.Swing.PanelBackground panelBackground4;
    private GUI.Comp.Swing.PanelBackground panelBackground5;
    private GUI.Comp.Swing.PanelBackground panelBackground6;
    private GUI.Comp.Swing.PanelBackground panelBackground7;
    private GUI.Comp.Swing.PanelBackground panelBackground8;
    private GUI.Comp.Swing.PanelBackground panelBackground9;
    private GUI.Comp.Swing.PanelBackground pnAnwser;
    private GUI.Comp.Swing.PanelBackground pnBottom;
    private GUI.Comp.Swing.PanelBackground pnCenter;
    private GUI.Comp.Swing.PanelBackground pnQuestion;
    private GUI.Comp.Swing.PanelBackground pnTop;
    // End of variables declaration//GEN-END:variables
}
