/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Comp.Dialog;

/**
 *
 * @author nguye
 */
public class DialogUser extends javax.swing.JDialog {

    /**
     * Creates new form DialogUser
     */
    public DialogUser(java.awt.Frame parent , boolean modal) {
        super(parent,modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground2 = new GUI.Comp.Swing.PanelBackground();
        panelBackground3 = new GUI.Comp.Swing.PanelBackground();
        panelBackground4 = new GUI.Comp.Swing.PanelBackground();
        panelBackground5 = new GUI.Comp.Swing.PanelBackground();
        pnCenter = new GUI.Comp.Swing.PanelBackground();
        pnTop = new GUI.Comp.Swing.PanelBackground();
        pnAnwser = new GUI.Comp.Swing.PanelBackground();
        jLabel5 = new javax.swing.JLabel();
        panelBackground7 = new GUI.Comp.Swing.PanelBackground();
        panelBackground25 = new GUI.Comp.Swing.PanelBackground();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panelBackground26 = new GUI.Comp.Swing.PanelBackground();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        panelBackground35 = new GUI.Comp.Swing.PanelBackground();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        pnBottom = new GUI.Comp.Swing.PanelBackground();
        line = new GUI.Comp.Swing.PanelBackground();
        panelBackground13 = new GUI.Comp.Swing.PanelBackground();
        panelBackground27 = new GUI.Comp.Swing.PanelBackground();
        panelBackground32 = new GUI.Comp.Swing.PanelBackground();
        jButton4 = new javax.swing.JButton();
        panelBackground33 = new GUI.Comp.Swing.PanelBackground();
        panelBackground34 = new GUI.Comp.Swing.PanelBackground();

        setLayout(new java.awt.BorderLayout());

        panelBackground2.setMinimumSize(new java.awt.Dimension(100, 20));
        panelBackground2.setPreferredSize(new java.awt.Dimension(995, 20));

        javax.swing.GroupLayout panelBackground2Layout = new javax.swing.GroupLayout(panelBackground2);
        panelBackground2.setLayout(panelBackground2Layout);
        panelBackground2Layout.setHorizontalGroup(
            panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        panelBackground2Layout.setVerticalGroup(
            panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(panelBackground2, java.awt.BorderLayout.PAGE_START);

        panelBackground3.setPreferredSize(new java.awt.Dimension(20, 616));

        javax.swing.GroupLayout panelBackground3Layout = new javax.swing.GroupLayout(panelBackground3);
        panelBackground3.setLayout(panelBackground3Layout);
        panelBackground3Layout.setHorizontalGroup(
            panelBackground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelBackground3Layout.setVerticalGroup(
            panelBackground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        add(panelBackground3, java.awt.BorderLayout.LINE_START);

        panelBackground4.setPreferredSize(new java.awt.Dimension(20, 616));

        javax.swing.GroupLayout panelBackground4Layout = new javax.swing.GroupLayout(panelBackground4);
        panelBackground4.setLayout(panelBackground4Layout);
        panelBackground4Layout.setHorizontalGroup(
            panelBackground4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelBackground4Layout.setVerticalGroup(
            panelBackground4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        add(panelBackground4, java.awt.BorderLayout.LINE_END);

        panelBackground5.setMinimumSize(new java.awt.Dimension(100, 20));
        panelBackground5.setPreferredSize(new java.awt.Dimension(995, 20));

        javax.swing.GroupLayout panelBackground5Layout = new javax.swing.GroupLayout(panelBackground5);
        panelBackground5.setLayout(panelBackground5Layout);
        panelBackground5Layout.setHorizontalGroup(
            panelBackground5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        panelBackground5Layout.setVerticalGroup(
            panelBackground5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(panelBackground5, java.awt.BorderLayout.PAGE_END);

        pnCenter.setLayout(new java.awt.BorderLayout(0, 15));

        pnTop.setLayout(new java.awt.GridLayout(2, 1, 0, 15));

        pnAnwser.setPreferredSize(new java.awt.Dimension(138, 20));
        pnAnwser.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel5.setText("Thêm người dùng");
        jLabel5.setMaximumSize(new java.awt.Dimension(138, 40));
        jLabel5.setMinimumSize(new java.awt.Dimension(138, 40));
        jLabel5.setPreferredSize(new java.awt.Dimension(138, 40));
        pnAnwser.add(jLabel5, java.awt.BorderLayout.PAGE_START);
        jLabel5.getAccessibleContext().setAccessibleDescription("");

        pnTop.add(pnAnwser);

        panelBackground7.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        panelBackground25.setLayout(new java.awt.BorderLayout());

        jTextField6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextField6.setText("jTextField1");
        jTextField6.setMinimumSize(new java.awt.Dimension(64, 30));
        jTextField6.setPreferredSize(new java.awt.Dimension(700, 30));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panelBackground25.add(jTextField6, java.awt.BorderLayout.CENTER);

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel8.setText("Tên người dùng:");
        panelBackground25.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        panelBackground7.add(panelBackground25);

        panelBackground26.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel9.setText("Email:");
        panelBackground26.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        jTextField7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextField7.setText("jTextField1");
        jTextField7.setMinimumSize(new java.awt.Dimension(64, 30));
        jTextField7.setPreferredSize(new java.awt.Dimension(700, 30));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        panelBackground26.add(jTextField7, java.awt.BorderLayout.CENTER);

        panelBackground7.add(panelBackground26);

        panelBackground35.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel10.setText("Mật khẩu:");
        panelBackground35.add(jLabel10, java.awt.BorderLayout.PAGE_START);

        jTextField8.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextField8.setText("jTextField1");
        jTextField8.setMinimumSize(new java.awt.Dimension(64, 30));
        jTextField8.setPreferredSize(new java.awt.Dimension(700, 30));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        panelBackground35.add(jTextField8, java.awt.BorderLayout.CENTER);

        panelBackground7.add(panelBackground35);

        pnTop.add(panelBackground7);

        pnCenter.add(pnTop, java.awt.BorderLayout.CENTER);

        pnBottom.setForeground(new java.awt.Color(204, 204, 204));
        pnBottom.setPreferredSize(new java.awt.Dimension(832, 100));
        pnBottom.setLayout(new java.awt.BorderLayout());

        line.setBackground(new java.awt.Color(204, 204, 204));
        line.setPreferredSize(new java.awt.Dimension(832, 1));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnBottom.add(line, java.awt.BorderLayout.PAGE_START);

        panelBackground13.setLayout(new java.awt.GridLayout(2, 1));

        panelBackground27.setLayout(new java.awt.BorderLayout());

        panelBackground32.setPreferredSize(new java.awt.Dimension(75, 49));
        panelBackground32.setLayout(new java.awt.BorderLayout());

        jButton4.setBackground(new java.awt.Color(225, 99, 73));
        jButton4.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Lưu");
        panelBackground32.add(jButton4, java.awt.BorderLayout.CENTER);

        panelBackground33.setPreferredSize(new java.awt.Dimension(100, 5));

        javax.swing.GroupLayout panelBackground33Layout = new javax.swing.GroupLayout(panelBackground33);
        panelBackground33.setLayout(panelBackground33Layout);
        panelBackground33Layout.setHorizontalGroup(
            panelBackground33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        panelBackground33Layout.setVerticalGroup(
            panelBackground33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        panelBackground32.add(panelBackground33, java.awt.BorderLayout.PAGE_START);

        panelBackground34.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout panelBackground34Layout = new javax.swing.GroupLayout(panelBackground34);
        panelBackground34.setLayout(panelBackground34Layout);
        panelBackground34Layout.setHorizontalGroup(
            panelBackground34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        panelBackground34Layout.setVerticalGroup(
            panelBackground34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelBackground32.add(panelBackground34, java.awt.BorderLayout.PAGE_END);

        panelBackground27.add(panelBackground32, java.awt.BorderLayout.LINE_END);

        panelBackground13.add(panelBackground27);

        pnBottom.add(panelBackground13, java.awt.BorderLayout.CENTER);

        pnCenter.add(pnBottom, java.awt.BorderLayout.PAGE_END);

        add(pnCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private GUI.Comp.Swing.PanelBackground line;
    private GUI.Comp.Swing.PanelBackground panelBackground13;
    private GUI.Comp.Swing.PanelBackground panelBackground2;
    private GUI.Comp.Swing.PanelBackground panelBackground25;
    private GUI.Comp.Swing.PanelBackground panelBackground26;
    private GUI.Comp.Swing.PanelBackground panelBackground27;
    private GUI.Comp.Swing.PanelBackground panelBackground3;
    private GUI.Comp.Swing.PanelBackground panelBackground32;
    private GUI.Comp.Swing.PanelBackground panelBackground33;
    private GUI.Comp.Swing.PanelBackground panelBackground34;
    private GUI.Comp.Swing.PanelBackground panelBackground35;
    private GUI.Comp.Swing.PanelBackground panelBackground4;
    private GUI.Comp.Swing.PanelBackground panelBackground5;
    private GUI.Comp.Swing.PanelBackground panelBackground7;
    private GUI.Comp.Swing.PanelBackground pnAnwser;
    private GUI.Comp.Swing.PanelBackground pnBottom;
    private GUI.Comp.Swing.PanelBackground pnCenter;
    private GUI.Comp.Swing.PanelBackground pnTop;
    // End of variables declaration//GEN-END:variables
}
