/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Comp.Dialog;

import BUS.AnswerBUS;
import BUS.QuestionBUS;
import BUS.TopicBUS;
import DAO.AnswerDAO;
import DTO.AnswerDTO;
import DTO.QuestionDTO;
import DTO.TopicDTO;
import java.awt.Image;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.lang.reflect.Array;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author quang
 */
public class DialogQuestion extends javax.swing.JDialog {
    private AnswerBUS anwserBUS = new AnswerBUS();
    private QuestionBUS questionBUS = new QuestionBUS();
    private List<TopicDTO> listTopic = new ArrayList<>();
    private TopicBUS topicBUS = new TopicBUS();

    
    private List<JRadioButton> listRadio = new ArrayList<>();
    private List<JTextField> listTxt = new ArrayList<>();
    /**
     * Creates new form DialogQuestion
     */
    public DialogQuestion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        renderTopic();
        listRadio.add(rd1);
        listRadio.add(rd2);
        listRadio.add(rd3);
        listRadio.add(rd4);
        listRadio.add(rd5);
        
        listTxt.add(txtAws1);
        listTxt.add(txtAws2);
        listTxt.add(txtAws3);
        listTxt.add(txtAws4);
        listTxt.add(txtAws5);
        

    }
    
    public void setData(QuestionDTO question) {
        System.out.println("hihi");
        txtCauHoi.setText(question.getContent());
        Path destinationFile = Paths.get(System.getProperty("user.dir") + "/src/GUI/Image/" + question.getPicture());
        Image img = new ImageIcon(destinationFile.toString()).getImage().getScaledInstance(300, 207, Image.SCALE_SMOOTH);
        txtImg.setIcon(new ImageIcon(img));
        txtImg.setName(question.getPicture());
        for (int i = 0; i < listTopic.size(); i++) {
            if (listTopic.get(i).getId() == question.getTopicId()) {
                cbxChuDe.setSelectedIndex(i);
                break;
            }
        }
        cbxDoKho.setSelectedIndex(question.getLevel().equals("Dễ") ? 0 : 
                question.getLevel().equals("Trung bình") ? 1 : 2);
        
        List<AnswerDTO> listAnsw = anwserBUS.getAnswerByQuestionId(question.getId());
        System.out.println(listAnsw.size());
        for(int i = 0; i < listAnsw.size(); i++) {
            listTxt.get(i).setText(listAnsw.get(i).getContent());
            if (listAnsw.get(i).isIsRight()) {
                listRadio.get(i).setSelected(true);
            }
        }
        
        
    }
    
    private void renderTopic() {
       listTopic = topicBUS.getAllTopic();
       cbxChuDe.removeAllItems();
       for (TopicDTO topic : listTopic) {
           cbxChuDe.addItem(topic.getTitle());
       }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBackground1 = new GUI.Comp.Swing.PanelBackground();
        panelBackground2 = new GUI.Comp.Swing.PanelBackground();
        panelBackground3 = new GUI.Comp.Swing.PanelBackground();
        panelBackground4 = new GUI.Comp.Swing.PanelBackground();
        panelBackground5 = new GUI.Comp.Swing.PanelBackground();
        pnCenter = new GUI.Comp.Swing.PanelBackground();
        pnTop = new GUI.Comp.Swing.PanelBackground();
        pnQuestion = new GUI.Comp.Swing.PanelBackground();
        jLabel1 = new javax.swing.JLabel();
        panelBackground6 = new GUI.Comp.Swing.PanelBackground();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCauHoi = new javax.swing.JTextArea();
        panelBackground10 = new GUI.Comp.Swing.PanelBackground();
        panelBackground11 = new GUI.Comp.Swing.PanelBackground();
        btnThemAnh = new javax.swing.JButton();
        txtImg = new javax.swing.JLabel();
        pnAnwser = new GUI.Comp.Swing.PanelBackground();
        jLabel2 = new javax.swing.JLabel();
        panelBackground7 = new GUI.Comp.Swing.PanelBackground();
        pnTraLoi1 = new GUI.Comp.Swing.PanelBackground();
        rd1 = new javax.swing.JRadioButton();
        txtAws1 = new javax.swing.JTextField();
        panelBackground12 = new GUI.Comp.Swing.PanelBackground();
        jButton2 = new javax.swing.JButton();
        panelBackground9 = new GUI.Comp.Swing.PanelBackground();
        jButton1 = new javax.swing.JButton();
        pnTraLoi2 = new GUI.Comp.Swing.PanelBackground();
        rd2 = new javax.swing.JRadioButton();
        txtAws2 = new javax.swing.JTextField();
        panelBackground17 = new GUI.Comp.Swing.PanelBackground();
        jButton5 = new javax.swing.JButton();
        panelBackground18 = new GUI.Comp.Swing.PanelBackground();
        jButton6 = new javax.swing.JButton();
        pnTraLoi3 = new GUI.Comp.Swing.PanelBackground();
        rd3 = new javax.swing.JRadioButton();
        txtAws3 = new javax.swing.JTextField();
        panelBackground14 = new GUI.Comp.Swing.PanelBackground();
        jButton3 = new javax.swing.JButton();
        panelBackground15 = new GUI.Comp.Swing.PanelBackground();
        jButton7 = new javax.swing.JButton();
        pnTraLoi4 = new GUI.Comp.Swing.PanelBackground();
        rd4 = new javax.swing.JRadioButton();
        txtAws4 = new javax.swing.JTextField();
        panelBackground19 = new GUI.Comp.Swing.PanelBackground();
        jButton8 = new javax.swing.JButton();
        panelBackground20 = new GUI.Comp.Swing.PanelBackground();
        jButton9 = new javax.swing.JButton();
        pnTraLoi5 = new GUI.Comp.Swing.PanelBackground();
        rd5 = new javax.swing.JRadioButton();
        txtAws5 = new javax.swing.JTextField();
        panelBackground21 = new GUI.Comp.Swing.PanelBackground();
        jButton10 = new javax.swing.JButton();
        panelBackground22 = new GUI.Comp.Swing.PanelBackground();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        pnBottom = new GUI.Comp.Swing.PanelBackground();
        line = new GUI.Comp.Swing.PanelBackground();
        panelBackground13 = new GUI.Comp.Swing.PanelBackground();
        jLabel3 = new javax.swing.JLabel();
        panelBackground27 = new GUI.Comp.Swing.PanelBackground();
        panelBackground28 = new GUI.Comp.Swing.PanelBackground();
        jLabel6 = new javax.swing.JLabel();
        panelBackground29 = new GUI.Comp.Swing.PanelBackground();
        cbxChuDe = new javax.swing.JComboBox<>();
        panelBackground30 = new GUI.Comp.Swing.PanelBackground();
        jLabel7 = new javax.swing.JLabel();
        panelBackground31 = new GUI.Comp.Swing.PanelBackground();
        cbxDoKho = new javax.swing.JComboBox<>();
        panelBackground32 = new GUI.Comp.Swing.PanelBackground();
        btnLuu = new javax.swing.JButton();
        panelBackground33 = new GUI.Comp.Swing.PanelBackground();
        panelBackground34 = new GUI.Comp.Swing.PanelBackground();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground1.setLayout(new java.awt.BorderLayout());

        panelBackground2.setMinimumSize(new java.awt.Dimension(100, 20));
        panelBackground2.setPreferredSize(new java.awt.Dimension(995, 20));

        javax.swing.GroupLayout panelBackground2Layout = new javax.swing.GroupLayout(panelBackground2);
        panelBackground2.setLayout(panelBackground2Layout);
        panelBackground2Layout.setHorizontalGroup(
            panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        panelBackground2Layout.setVerticalGroup(
            panelBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelBackground1.add(panelBackground2, java.awt.BorderLayout.PAGE_START);

        panelBackground3.setPreferredSize(new java.awt.Dimension(20, 616));

        javax.swing.GroupLayout panelBackground3Layout = new javax.swing.GroupLayout(panelBackground3);
        panelBackground3.setLayout(panelBackground3Layout);
        panelBackground3Layout.setHorizontalGroup(
            panelBackground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelBackground3Layout.setVerticalGroup(
            panelBackground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        panelBackground1.add(panelBackground3, java.awt.BorderLayout.LINE_START);

        panelBackground4.setPreferredSize(new java.awt.Dimension(20, 616));

        javax.swing.GroupLayout panelBackground4Layout = new javax.swing.GroupLayout(panelBackground4);
        panelBackground4.setLayout(panelBackground4Layout);
        panelBackground4Layout.setHorizontalGroup(
            panelBackground4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelBackground4Layout.setVerticalGroup(
            panelBackground4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        panelBackground1.add(panelBackground4, java.awt.BorderLayout.LINE_END);

        panelBackground5.setMinimumSize(new java.awt.Dimension(100, 20));
        panelBackground5.setPreferredSize(new java.awt.Dimension(995, 20));

        javax.swing.GroupLayout panelBackground5Layout = new javax.swing.GroupLayout(panelBackground5);
        panelBackground5.setLayout(panelBackground5Layout);
        panelBackground5Layout.setHorizontalGroup(
            panelBackground5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        panelBackground5Layout.setVerticalGroup(
            panelBackground5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelBackground1.add(panelBackground5, java.awt.BorderLayout.PAGE_END);

        pnCenter.setLayout(new java.awt.BorderLayout(0, 15));

        pnTop.setLayout(new java.awt.GridLayout(2, 1, 0, 15));

        pnQuestion.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel1.setText("Câu hỏi");
        pnQuestion.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        panelBackground6.setLayout(new javax.swing.BoxLayout(panelBackground6, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 96));

        txtCauHoi.setColumns(20);
        txtCauHoi.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtCauHoi.setLineWrap(true);
        txtCauHoi.setRows(5);
        jScrollPane1.setViewportView(txtCauHoi);

        panelBackground6.add(jScrollPane1);

        panelBackground10.setPreferredSize(new java.awt.Dimension(30, 241));

        javax.swing.GroupLayout panelBackground10Layout = new javax.swing.GroupLayout(panelBackground10);
        panelBackground10.setLayout(panelBackground10Layout);
        panelBackground10Layout.setHorizontalGroup(
            panelBackground10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        panelBackground10Layout.setVerticalGroup(
            panelBackground10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        panelBackground6.add(panelBackground10);

        panelBackground11.setPreferredSize(new java.awt.Dimension(350, 241));
        panelBackground11.setLayout(new java.awt.BorderLayout());

        btnThemAnh.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnThemAnh.setText("Thêm hình ảnh");
        btnThemAnh.setPreferredSize(new java.awt.Dimension(137, 35));
        btnThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemAnhActionPerformed(evt);
            }
        });
        panelBackground11.add(btnThemAnh, java.awt.BorderLayout.PAGE_END);

        txtImg.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/minus-sign-inside-a-black-circle (1).png"))); // NOI18N
        txtImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtImg.setName(""); // NOI18N
        panelBackground11.add(txtImg, java.awt.BorderLayout.CENTER);

        panelBackground6.add(panelBackground11);

        pnQuestion.add(panelBackground6, java.awt.BorderLayout.CENTER);

        pnTop.add(pnQuestion);

        pnAnwser.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel2.setText("Câu trả lời");
        pnAnwser.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        panelBackground7.setLayout(new java.awt.GridLayout(6, 1, 0, 5));

        pnTraLoi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(rd1);
        rd1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        rd1.setPreferredSize(new java.awt.Dimension(25, 30));
        pnTraLoi1.add(rd1);

        txtAws1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtAws1.setMinimumSize(new java.awt.Dimension(64, 30));
        txtAws1.setPreferredSize(new java.awt.Dimension(700, 30));
        pnTraLoi1.add(txtAws1);

        panelBackground12.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground12Layout = new javax.swing.GroupLayout(panelBackground12);
        panelBackground12.setLayout(panelBackground12Layout);
        panelBackground12Layout.setHorizontalGroup(
            panelBackground12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground12Layout.setVerticalGroup(
            panelBackground12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnTraLoi1.add(panelBackground12);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/image.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        pnTraLoi1.add(jButton2);

        panelBackground9.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground9Layout = new javax.swing.GroupLayout(panelBackground9);
        panelBackground9.setLayout(panelBackground9Layout);
        panelBackground9Layout.setHorizontalGroup(
            panelBackground9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground9Layout.setVerticalGroup(
            panelBackground9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnTraLoi1.add(panelBackground9);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/delete.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        pnTraLoi1.add(jButton1);

        panelBackground7.add(pnTraLoi1);

        pnTraLoi2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(rd2);
        rd2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        rd2.setPreferredSize(new java.awt.Dimension(25, 30));
        pnTraLoi2.add(rd2);

        txtAws2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtAws2.setMinimumSize(new java.awt.Dimension(64, 30));
        txtAws2.setPreferredSize(new java.awt.Dimension(700, 30));
        pnTraLoi2.add(txtAws2);

        panelBackground17.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground17Layout = new javax.swing.GroupLayout(panelBackground17);
        panelBackground17.setLayout(panelBackground17Layout);
        panelBackground17Layout.setHorizontalGroup(
            panelBackground17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground17Layout.setVerticalGroup(
            panelBackground17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnTraLoi2.add(panelBackground17);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/image.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setPreferredSize(new java.awt.Dimension(30, 30));
        pnTraLoi2.add(jButton5);

        panelBackground18.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground18Layout = new javax.swing.GroupLayout(panelBackground18);
        panelBackground18.setLayout(panelBackground18Layout);
        panelBackground18Layout.setHorizontalGroup(
            panelBackground18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground18Layout.setVerticalGroup(
            panelBackground18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnTraLoi2.add(panelBackground18);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/delete.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnTraLoi2.add(jButton6);

        panelBackground7.add(pnTraLoi2);

        pnTraLoi3.setEnabled(false);
        pnTraLoi3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(rd3);
        rd3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        rd3.setPreferredSize(new java.awt.Dimension(25, 30));
        pnTraLoi3.add(rd3);

        txtAws3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtAws3.setMinimumSize(new java.awt.Dimension(64, 30));
        txtAws3.setPreferredSize(new java.awt.Dimension(700, 30));
        pnTraLoi3.add(txtAws3);

        panelBackground14.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground14Layout = new javax.swing.GroupLayout(panelBackground14);
        panelBackground14.setLayout(panelBackground14Layout);
        panelBackground14Layout.setHorizontalGroup(
            panelBackground14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground14Layout.setVerticalGroup(
            panelBackground14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnTraLoi3.add(panelBackground14);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/image.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(30, 30));
        pnTraLoi3.add(jButton3);

        panelBackground15.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground15Layout = new javax.swing.GroupLayout(panelBackground15);
        panelBackground15.setLayout(panelBackground15Layout);
        panelBackground15Layout.setHorizontalGroup(
            panelBackground15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground15Layout.setVerticalGroup(
            panelBackground15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnTraLoi3.add(panelBackground15);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/delete.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setPreferredSize(new java.awt.Dimension(30, 30));
        pnTraLoi3.add(jButton7);

        panelBackground7.add(pnTraLoi3);

        pnTraLoi4.setEnabled(false);
        pnTraLoi4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(rd4);
        rd4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        rd4.setPreferredSize(new java.awt.Dimension(25, 30));
        pnTraLoi4.add(rd4);

        txtAws4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtAws4.setMinimumSize(new java.awt.Dimension(64, 30));
        txtAws4.setPreferredSize(new java.awt.Dimension(700, 30));
        pnTraLoi4.add(txtAws4);

        panelBackground19.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground19Layout = new javax.swing.GroupLayout(panelBackground19);
        panelBackground19.setLayout(panelBackground19Layout);
        panelBackground19Layout.setHorizontalGroup(
            panelBackground19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground19Layout.setVerticalGroup(
            panelBackground19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnTraLoi4.add(panelBackground19);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/image.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setPreferredSize(new java.awt.Dimension(30, 30));
        pnTraLoi4.add(jButton8);

        panelBackground20.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground20Layout = new javax.swing.GroupLayout(panelBackground20);
        panelBackground20.setLayout(panelBackground20Layout);
        panelBackground20Layout.setHorizontalGroup(
            panelBackground20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground20Layout.setVerticalGroup(
            panelBackground20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnTraLoi4.add(panelBackground20);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/delete.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setPreferredSize(new java.awt.Dimension(30, 30));
        pnTraLoi4.add(jButton9);

        panelBackground7.add(pnTraLoi4);

        pnTraLoi5.setEnabled(false);
        pnTraLoi5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(rd5);
        rd5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        rd5.setPreferredSize(new java.awt.Dimension(25, 30));
        pnTraLoi5.add(rd5);

        txtAws5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtAws5.setMinimumSize(new java.awt.Dimension(64, 30));
        txtAws5.setPreferredSize(new java.awt.Dimension(700, 30));
        pnTraLoi5.add(txtAws5);

        panelBackground21.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground21Layout = new javax.swing.GroupLayout(panelBackground21);
        panelBackground21.setLayout(panelBackground21Layout);
        panelBackground21Layout.setHorizontalGroup(
            panelBackground21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground21Layout.setVerticalGroup(
            panelBackground21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnTraLoi5.add(panelBackground21);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/image.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setPreferredSize(new java.awt.Dimension(30, 30));
        pnTraLoi5.add(jButton10);

        panelBackground22.setPreferredSize(new java.awt.Dimension(5, 30));

        javax.swing.GroupLayout panelBackground22Layout = new javax.swing.GroupLayout(panelBackground22);
        panelBackground22.setLayout(panelBackground22Layout);
        panelBackground22Layout.setHorizontalGroup(
            panelBackground22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelBackground22Layout.setVerticalGroup(
            panelBackground22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnTraLoi5.add(panelBackground22);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Comp/Icon/delete.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setPreferredSize(new java.awt.Dimension(30, 30));
        pnTraLoi5.add(jButton11);

        panelBackground7.add(pnTraLoi5);

        jButton12.setBackground(new java.awt.Color(243, 215, 208));
        jButton12.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jButton12.setText("Thêm câu trả lời");
        jButton12.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBackground7.add(jButton12);

        pnAnwser.add(panelBackground7, java.awt.BorderLayout.CENTER);

        pnTop.add(pnAnwser);

        pnCenter.add(pnTop, java.awt.BorderLayout.CENTER);

        pnBottom.setForeground(new java.awt.Color(204, 204, 204));
        pnBottom.setPreferredSize(new java.awt.Dimension(832, 100));
        pnBottom.setLayout(new java.awt.BorderLayout());

        line.setBackground(new java.awt.Color(204, 204, 204));
        line.setPreferredSize(new java.awt.Dimension(832, 1));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnBottom.add(line, java.awt.BorderLayout.PAGE_START);

        panelBackground13.setLayout(new java.awt.GridLayout(2, 1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setText("Cài đặt");
        panelBackground13.add(jLabel3);

        panelBackground27.setLayout(new java.awt.BorderLayout());

        panelBackground28.setPreferredSize(new java.awt.Dimension(500, 49));
        panelBackground28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setText("Chủ đề");
        panelBackground28.add(jLabel6);

        panelBackground29.setPreferredSize(new java.awt.Dimension(10, 30));

        javax.swing.GroupLayout panelBackground29Layout = new javax.swing.GroupLayout(panelBackground29);
        panelBackground29.setLayout(panelBackground29Layout);
        panelBackground29Layout.setHorizontalGroup(
            panelBackground29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelBackground29Layout.setVerticalGroup(
            panelBackground29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground28.add(panelBackground29);

        cbxChuDe.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        cbxChuDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxChuDe.setPreferredSize(new java.awt.Dimension(150, 30));
        panelBackground28.add(cbxChuDe);

        panelBackground30.setPreferredSize(new java.awt.Dimension(10, 30));

        javax.swing.GroupLayout panelBackground30Layout = new javax.swing.GroupLayout(panelBackground30);
        panelBackground30.setLayout(panelBackground30Layout);
        panelBackground30Layout.setHorizontalGroup(
            panelBackground30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelBackground30Layout.setVerticalGroup(
            panelBackground30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground28.add(panelBackground30);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setText("Độ khó");
        panelBackground28.add(jLabel7);

        panelBackground31.setPreferredSize(new java.awt.Dimension(10, 30));

        javax.swing.GroupLayout panelBackground31Layout = new javax.swing.GroupLayout(panelBackground31);
        panelBackground31.setLayout(panelBackground31Layout);
        panelBackground31Layout.setHorizontalGroup(
            panelBackground31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelBackground31Layout.setVerticalGroup(
            panelBackground31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelBackground28.add(panelBackground31);

        cbxDoKho.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        cbxDoKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dễ", "Trung bình", "Khó" }));
        cbxDoKho.setPreferredSize(new java.awt.Dimension(150, 30));
        panelBackground28.add(cbxDoKho);

        panelBackground27.add(panelBackground28, java.awt.BorderLayout.LINE_START);

        panelBackground32.setPreferredSize(new java.awt.Dimension(75, 49));
        panelBackground32.setLayout(new java.awt.BorderLayout());

        btnLuu.setBackground(new java.awt.Color(225, 99, 73));
        btnLuu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        panelBackground32.add(btnLuu, java.awt.BorderLayout.CENTER);

        panelBackground33.setPreferredSize(new java.awt.Dimension(100, 5));

        javax.swing.GroupLayout panelBackground33Layout = new javax.swing.GroupLayout(panelBackground33);
        panelBackground33.setLayout(panelBackground33Layout);
        panelBackground33Layout.setHorizontalGroup(
            panelBackground33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        panelBackground33Layout.setVerticalGroup(
            panelBackground33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        panelBackground32.add(panelBackground33, java.awt.BorderLayout.PAGE_START);

        panelBackground34.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout panelBackground34Layout = new javax.swing.GroupLayout(panelBackground34);
        panelBackground34.setLayout(panelBackground34Layout);
        panelBackground34Layout.setHorizontalGroup(
            panelBackground34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        panelBackground34Layout.setVerticalGroup(
            panelBackground34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelBackground32.add(panelBackground34, java.awt.BorderLayout.PAGE_END);

        panelBackground27.add(panelBackground32, java.awt.BorderLayout.LINE_END);

        panelBackground13.add(panelBackground27);

        pnBottom.add(panelBackground13, java.awt.BorderLayout.CENTER);

        pnCenter.add(pnBottom, java.awt.BorderLayout.PAGE_END);

        panelBackground1.add(pnCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemAnhActionPerformed
        String regex = "^.+\\.(jpg|jpeg|png|gif|bmp)$";
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        if (file.getSelectedFile() == null) {
            return;
        }
        String pathSource = file.getSelectedFile().getAbsolutePath();
        String nameFile = pathSource.substring(pathSource.lastIndexOf("\\") + 1);
        if (nameFile.matches(regex)) {
            Path sourceFile = Paths.get(pathSource);
            Path destinationFile = Paths.get(System.getProperty("user.dir") + "/src/GUI/Image/" + nameFile);
            System.out.println(sourceFile.toString());
            System.out.println(destinationFile.toString());
            try {
                Files.copy(sourceFile, destinationFile, StandardCopyOption.REPLACE_EXISTING);
                Image img = new ImageIcon(destinationFile.toString()).getImage().getScaledInstance(300, 207, Image.SCALE_SMOOTH);
                txtImg.setIcon(new ImageIcon(img));
                txtImg.setName(nameFile);
            } 
            catch (IOException ex) {
            }

         
        }
        else {
            JOptionPane.showMessageDialog(this, "File bạn chọn không phải là ẢNH");
        }
    }//GEN-LAST:event_btnThemAnhActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
//        System.out.println(rd1.isSelected() + " " + txtAws1.getText());
//        System.out.println(rd2.isSelected() + " " + txtAws2.getText());
//        System.out.println(rd3.isSelected() + " " + txtAws3.getText());
//        System.out.println(rd4.isSelected() + " " + txtAws4.getText());
//        System.out.println(rd5.isSelected() + " " + txtAws5.getText());
//        
        QuestionDTO question = QuestionDTO.builder()
                .setContent(txtCauHoi.getText())
                .setPicture(txtImg.getName())
                .setLevel(cbxDoKho.getSelectedItem().toString())
                .setTopicId(listTopic.get(cbxChuDe.getSelectedIndex()).getId())
                .setStatus(true)
                .build();
        int idQuestion = questionBUS.createQuestion(question).getId();
        System.out.println(idQuestion + "");
       
        AnswerDTO aws1 = AnswerDTO.builder()
                .setContent(txtAws1.getText())
                .setIsRight(rd1.isSelected())
                .setQuestionId(idQuestion)
                .setStatus(true)
                .build();
        anwserBUS.createAnwser(aws1);
        AnswerDTO aws2 = AnswerDTO.builder()
                .setContent(txtAws2.getText())
                .setIsRight(rd2.isSelected())
                .setQuestionId(idQuestion)
                .setStatus(true)
                .build();
        anwserBUS.createAnwser(aws2);
        AnswerDTO aws3 = AnswerDTO.builder()
                .setContent(txtAws3.getText())
                .setIsRight(rd3.isSelected())
                .setQuestionId(idQuestion)
                .setStatus(true)
                .build();
        anwserBUS.createAnwser(aws3);
        AnswerDTO aws4 = AnswerDTO.builder()
                .setContent(txtAws4.getText())
                .setIsRight(rd4.isSelected())
                .setQuestionId(idQuestion)
                .setStatus(true)
                .build();
        anwserBUS.createAnwser(aws4);
        AnswerDTO aws5 = AnswerDTO.builder()
                .setContent(txtAws5.getText())
                .setIsRight(rd5.isSelected())
                .setQuestionId(idQuestion)
                .setStatus(true)
                .build();
        anwserBUS.createAnwser(aws5);
        
    }//GEN-LAST:event_btnLuuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogQuestion dialog = new DialogQuestion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThemAnh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxChuDe;
    private javax.swing.JComboBox<String> cbxDoKho;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.Comp.Swing.PanelBackground line;
    private GUI.Comp.Swing.PanelBackground panelBackground1;
    private GUI.Comp.Swing.PanelBackground panelBackground10;
    private GUI.Comp.Swing.PanelBackground panelBackground11;
    private GUI.Comp.Swing.PanelBackground panelBackground12;
    private GUI.Comp.Swing.PanelBackground panelBackground13;
    private GUI.Comp.Swing.PanelBackground panelBackground14;
    private GUI.Comp.Swing.PanelBackground panelBackground15;
    private GUI.Comp.Swing.PanelBackground panelBackground17;
    private GUI.Comp.Swing.PanelBackground panelBackground18;
    private GUI.Comp.Swing.PanelBackground panelBackground19;
    private GUI.Comp.Swing.PanelBackground panelBackground2;
    private GUI.Comp.Swing.PanelBackground panelBackground20;
    private GUI.Comp.Swing.PanelBackground panelBackground21;
    private GUI.Comp.Swing.PanelBackground panelBackground22;
    private GUI.Comp.Swing.PanelBackground panelBackground27;
    private GUI.Comp.Swing.PanelBackground panelBackground28;
    private GUI.Comp.Swing.PanelBackground panelBackground29;
    private GUI.Comp.Swing.PanelBackground panelBackground3;
    private GUI.Comp.Swing.PanelBackground panelBackground30;
    private GUI.Comp.Swing.PanelBackground panelBackground31;
    private GUI.Comp.Swing.PanelBackground panelBackground32;
    private GUI.Comp.Swing.PanelBackground panelBackground33;
    private GUI.Comp.Swing.PanelBackground panelBackground34;
    private GUI.Comp.Swing.PanelBackground panelBackground4;
    private GUI.Comp.Swing.PanelBackground panelBackground5;
    private GUI.Comp.Swing.PanelBackground panelBackground6;
    private GUI.Comp.Swing.PanelBackground panelBackground7;
    private GUI.Comp.Swing.PanelBackground panelBackground9;
    private GUI.Comp.Swing.PanelBackground pnAnwser;
    private GUI.Comp.Swing.PanelBackground pnBottom;
    private GUI.Comp.Swing.PanelBackground pnCenter;
    private GUI.Comp.Swing.PanelBackground pnQuestion;
    private GUI.Comp.Swing.PanelBackground pnTop;
    private GUI.Comp.Swing.PanelBackground pnTraLoi1;
    private GUI.Comp.Swing.PanelBackground pnTraLoi2;
    private GUI.Comp.Swing.PanelBackground pnTraLoi3;
    private GUI.Comp.Swing.PanelBackground pnTraLoi4;
    private GUI.Comp.Swing.PanelBackground pnTraLoi5;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JRadioButton rd3;
    private javax.swing.JRadioButton rd4;
    private javax.swing.JRadioButton rd5;
    private javax.swing.JTextField txtAws1;
    private javax.swing.JTextField txtAws2;
    private javax.swing.JTextField txtAws3;
    private javax.swing.JTextField txtAws4;
    private javax.swing.JTextField txtAws5;
    private javax.swing.JTextArea txtCauHoi;
    private javax.swing.JLabel txtImg;
    // End of variables declaration//GEN-END:variables
}
