package GUI.Comp.Dialog;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import BUS.ExamBUS;
import BUS.TestBUS;
import BUS.QuestionBUS;
import DTO.ExamDTO;
import DTO.QuestionDTO;
import DTO.TestDTO;
import GUI.Custom.ExportDocx;
import BUS.AnswerBUS;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;

/**
 *
 * @author Minh Phuc
 */
public class DialogExams extends javax.swing.JDialog {
    private ArrayList<String> testList = new ArrayList<>();
    private TestBUS testExamBUS = new TestBUS();
    private ExamBUS BUS = new ExamBUS();
    private QuestionBUS questionBUS = new QuestionBUS();
    private AnswerBUS answerBUS = new AnswerBUS();
    private String examCode;
    private String testCode;
    private List<QuestionDTO> questions;

    /**
     * Creates new form DialogExams
     * 
     * @param testCode
     */
    public DialogExams(java.awt.Frame parent, boolean modal, String examCode, String testCode) {
        super(parent, modal);
        this.examCode = examCode;
        this.testCode = testCode;
        initComponents();
        loadTestDetails();
        setLocationRelativeTo(null);
        updateButton();
    }

    private void loadTestDetails() {
        TestDTO testExam = testExamBUS.findByTestCode(testCode);
        if (testExam != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            jLabel2.setText(dateFormat.format(testExam.getTestDate()));
            jLabel3.setText(testExam.getTestTime() + " phút");
        }
    }

    private void updateButton() {
        label1.setText("Xem chi tiết đề thi");
        label1.setFont(new java.awt.Font("Roboto", java.awt.Font.BOLD, 18));
        jButton2.setText("Xuất PDF");
        questions = questionBUS.getQuestionByExamCode(examCode);

        for (ActionListener al : jButton2.getActionListeners()) {
            jButton2.removeActionListener(al); // Xóa action cũ
        }
        // Thêm action mới
        jButton2.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "Xuất đề thi dưới dạng PDF " + examCode);
            exportExam(questions, examCode);
        });

        // Clear the table
        DefaultTableModel model = (DefaultTableModel) tbCauHoi.getModel();
        model.setRowCount(0);

        // Add questions to the table
        for (QuestionDTO question : questions) {
            model.addRow(new Object[] { question.getId(), question.getContent(), formatLevel(question.getLevel()) });
        }

        model.fireTableDataChanged();
        tbCauHoi.setModel(model);
    }

    private String formatLevel(String level) {
        switch (level) {
            case "easy":
                return "Dễ";
            case "medium":
                return "Trung bình";
            case "diff":
                return "Khó";
            default:
                return "";
        }
    }

    // Sự kiện xuất đề thi
    private void exportExam(List<QuestionDTO> dataList, String examCode) {
        // Gọi hàm xuất đề thi
        ExportDocx.exportExamToDocx(examCode, dataList, answerBUS);
        JOptionPane.showMessageDialog(this, "Xuất đề thi thành công!");
        dispose(); // Đóng dialog
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCauHoi = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label1.setFont(new java.awt.Font("Roboto", 1, 18));
        label1.setText("Xem chi tiết đề thi");

        label2.setFont(new java.awt.Font("Roboto", 0, 14));
        label2.setText("Tên tổ hợp:");

        label3.setFont(new java.awt.Font("Roboto", 0, 14));
        label3.setText("Ngày thi:");

        label4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label4.setText("Thứ tự:");

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14));
        jLabel1.setText(examCode);

        tbCauHoi.setFont(new java.awt.Font("Roboto", 0, 16));
        tbCauHoi.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "STT", "Câu hỏi", "Độ khó"
                }));
        tbCauHoi.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tbCauHoi);

        jButton2.setBackground(new java.awt.Color(53, 80, 154));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 14));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Xuất PDF");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14));
        jLabel2.setText("");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14));
        jLabel3.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 583,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(27, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addContainerGap(27, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateLabel() {
        
        TestDTO selectedTestExam = (TestDTO) jComboBox1.getSelectedItem();
        String selectedOrder = (String) jComboBox2.getSelectedItem();
        jLabel1.setText(selectedTestExam.getTestCode() + selectedOrder);

        // Fetch questions based on the topic ID
        // int topicId = selectedTestExam.getTopicId();
        // List<QuestionDTO> temp = testExamBUS.getByTopicId(topicId);
        // questions = BUS.shuffleQuestions(temp);

        // Clear the table
        DefaultTableModel model = (DefaultTableModel) tbCauHoi.getModel();
        model.setRowCount(0);

        // Add questions to the table based on the number of questions for each level
        // int numEasy = selectedTestExam.getEasyQuestionCount();
        // int numMedium = selectedTestExam.getMediumQuestionCount();
        // int numDiff = selectedTestExam.getDiffQuestionCount();

        // int easyCount = 0, mediumCount = 0, diffCount = 0;

        // for (QuestionDTO question : questions) {
        //     if (question.getLevel().equals("Dễ") && easyCount < numEasy) {
        //         model.addRow(new Object[] { question.getId(), question.getContent(), question.getLevel() });
        //         easyCount++;
        //     } else if (question.getLevel().equals("Trung bình") && mediumCount < numMedium) {
        //         model.addRow(new Object[] { question.getId(), question.getContent(), question.getLevel() });
        //         mediumCount++;
        //     } else if (question.getLevel().equals("Khó") && diffCount < numDiff) {
        //         model.addRow(new Object[] { question.getId(), question.getContent(), question.getLevel() });
        //         diffCount++;
        //     }
        // }

        model.fireTableDataChanged();
        tbCauHoi.setModel(model);
    }

    private ExamDTO gatherData() {
        var testExam = (TestDTO) jComboBox1.getSelectedItem();

        return ExamDTO.builder()
                      .setTestCode(testExam.getTestCode())
                      .setExCode(jLabel1.getText())
                      .setExOrder((String)jComboBox2.getSelectedItem())
                      .setQuestions(questions)
                      .setStatus(true)
                      .build();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        ExamDTO exam = gatherData();
        if (BUS.addExam(exam) == null) JOptionPane.showMessageDialog(this, "Tạo đề thi thất bại");
        else JOptionPane.showMessageDialog(this, "Tạo đề thi thành công");
        this.dispose();
    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogExams.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogExams.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogExams.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogExams.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JTable tbCauHoi;
    // End of variables declaration//GEN-END:variables
}