/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Main;

import GUI.Comp.Panel.PanelRegister;
import GUI.Comp.Panel.PanelResetPassword;
import GUI.Comp.Panel.PannelLogin;
import Helper.ConnectDB;
import Helper.MyListener;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.nio.file.Paths;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import style.ColorConfig;

/**
 *
 * @author 84376
 */
public class Login2 extends javax.swing.JFrame implements PropertyChangeListener {
    /**
     * Creates new form Login2
     */
    public Login2() {
        initComponents();
        ConnectDB.getInstance().openConnect();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new Dimension(835, 560));
        setLocationRelativeTo(null);
        setResizable(false);
        MyListener.getInstance().addPropertyChangeListener(this);
        showForm(new PannelLogin());
        
        String linkImg = Paths.get(System.getProperty("user.dir") + "/src/GUI/Comp/Icon/logo1.jpg").toString();
        Image img = new ImageIcon(linkImg).getImage().getScaledInstance(417, 600, Image.SCALE_SMOOTH);
        txtImg.setIcon(new ImageIcon(img));
        
        setLocationRelativeTo(null);
    }
    
        public void showForm(JPanel com) {
        pnLeft.removeAll();
        pnLeft.add(com);
        pnLeft.revalidate();
        pnLeft.repaint();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground1 = new GUI.Comp.Swing.PanelBackground();
        pnLeft = new GUI.Comp.Swing.PanelBackground();
        panelBackground3 = new GUI.Comp.Swing.PanelBackground();
        txtImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelBackground1.setLayout(new java.awt.GridLayout(1, 2));

        pnLeft.setLayout(new java.awt.BorderLayout());
        panelBackground1.add(pnLeft);

        panelBackground3.setBackground(new java.awt.Color(255, 51, 102));
        panelBackground3.setLayout(new java.awt.BorderLayout());
        panelBackground3.add(txtImg, java.awt.BorderLayout.CENTER);

        panelBackground1.add(panelBackground3);

        getContentPane().add(panelBackground1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.registerCustomDefaultsSource("style");
        UIManager.put("TextField.font", style.MyFont.fontText);
        UIManager.put("Label.font", style.MyFont.fontText);
        UIManager.put("Button.font", style.MyFont.fontText);
        UIManager.put("Table.font", style.MyFont.fontText);
        UIManager.put("PasswordField.font", style.MyFont.fontText);
        UIManager.put("PasswordField.showRevealButton", true);
        UIManager.put("RootPane.background", new Color(255, 255, 255));
        UIManager.put("TitlePane.background", new Color(255, 255, 255));
        UIManager.put("TitlePane.foreground", new Color(0, 0, 0));
        UIManager.put("TitlePane.font", new Font("Roboto", Font.BOLD, 16));
        UIManager.put("TitlePane.centerTitle", true);
        UIManager.put("TableHeader.font", new Font("Roboto", Font.BOLD, 16));
        UIManager.put("TableHeader.separatorColor", new Color(0, 0, 0, 0));
        UIManager.put("Button.hoverBackground ", ColorConfig.LIGHT_BLUE);

        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Comp.Swing.PanelBackground panelBackground1;
    private GUI.Comp.Swing.PanelBackground panelBackground3;
    private GUI.Comp.Swing.PanelBackground pnLeft;
    private javax.swing.JLabel txtImg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals("loginSuccess")) {
            this.setVisible(false);
        }
        else if (evt.getPropertyName().equals("register")) {
            showForm(new PanelRegister());
        }
        else if (evt.getPropertyName().equals("resetPassword")) {
            PanelResetPassword resetForm = new PanelResetPassword();
            resetForm.setUserID(Integer.parseInt(evt.getNewValue().toString()));
            showForm(resetForm);
        }
        else if (evt.getPropertyName().equals("back_home")) {
            showForm(new PannelLogin());
        }
        
    }
}
