/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Comp.Panel;

import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import java.util.function.Consumer;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import style.ColorConfig;

/**
 *
 * @author pc
 */
public class PanelAnswers extends javax.swing.JPanel {
    private boolean isSelected = false;
    private char order;
    private String answ;
    private String path;

    private ArrayList<Consumer<Character>> onClickCallback = new ArrayList<>();

    /**
     * Creates new form PanelAnswers
     */
    public PanelAnswers() {
        initComponents();
    }
    
    public String getPath() {
        return this.path;
    }
    
    public void setData(char order, String answ, String path) {
        this.order = order;
        this.answ = answ;
        this.path = path;
        this.lbOrder.setText(order + ". ");
        this.lbAnsw.setText(answ);
        System.out.println(this.lbOrder.getText() + " " + this.lbAnsw.getText());
        if (path == null || path.isEmpty()) {
            this.lbImg.setIcon(null);
        }
        else {
            Image img = new ImageIcon(path).getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            this.lbImg.setIcon(new ImageIcon(img));
        }
    }
    
    public boolean isSelected() {
        return this.isSelected;
    }
    
    public void selected(boolean isSelected, boolean multiChoice) {
        this.isSelected = isSelected;
        if (isSelected) {
            Font oldFont = lbOrder.getFont();
            if (multiChoice == true) {
                lbOrder.setFont(oldFont.deriveFont(Font.BOLD, oldFont.getSize())); // Giữ nguyên size, chỉ đổi thành BOLD
                lbOrder.setForeground(ColorConfig.GREEN);
                lbAnsw.setFont(oldFont.deriveFont(Font.BOLD, oldFont.getSize()));
                lbAnsw.setForeground(ColorConfig.GREEN);
                main.setBackground(ColorConfig.LIGHT_GREEN);
            }
            else {
                lbOrder.setFont(oldFont.deriveFont(Font.BOLD, oldFont.getSize())); // Giữ nguyên size, chỉ đổi thành BOLD
                lbOrder.setForeground(ColorConfig.BLUE);
                lbAnsw.setFont(oldFont.deriveFont(Font.BOLD, oldFont.getSize()));
                lbAnsw.setForeground(ColorConfig.BLUE);
                main.setBackground(ColorConfig.LIGHT_BLUE);
            }

            invokeOnClickEvent();
        }
        else {
            Font oldFont = lbOrder.getFont();
            lbOrder.setFont(oldFont.deriveFont(Font.PLAIN, oldFont.getSize())); // Giữ nguyên size, chỉ đổi thành BOLD
            lbOrder.setForeground(ColorConfig.BLACK);
            lbAnsw.setFont(oldFont.deriveFont(Font.PLAIN, oldFont.getSize()));
            lbAnsw.setForeground(ColorConfig.BLACK);
            main.setBackground(ColorConfig.GREY_COLOR_BG);
        }
    }
    
    public char getOrder() {
        return order;
    }
    
    public String getAnsw() {
        return answ;
    }

    public void addOnClickCallback(Consumer<Character> callback) {
        onClickCallback.add(callback);
    }

    private void invokeOnClickEvent() {
        for (var callback : onClickCallback) {
            callback.accept(order);
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new GUI.Comp.Swing.PanelBackground();
        lbOrder = new javax.swing.JLabel();
        lbImg = new javax.swing.JLabel();
        lbAnsw = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLayout(new java.awt.BorderLayout());

        main.setBackground(new java.awt.Color(247, 247, 247));
        main.setLayout(new java.awt.BorderLayout());

        lbOrder.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lbOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOrder.setText("A.");
        lbOrder.setPreferredSize(new java.awt.Dimension(35, 30));
        main.add(lbOrder, java.awt.BorderLayout.LINE_START);

        lbImg.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lbImg.setPreferredSize(new java.awt.Dimension(200, 200));
        main.add(lbImg, java.awt.BorderLayout.LINE_END);

        lbAnsw.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lbAnsw.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbAnsw.setText("Aloaloaloasd");
        lbAnsw.setPreferredSize(new java.awt.Dimension(211, 30));
        main.add(lbAnsw, java.awt.BorderLayout.CENTER);

        add(main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAnsw;
    private javax.swing.JLabel lbImg;
    private javax.swing.JLabel lbOrder;
    private GUI.Comp.Swing.PanelBackground main;
    // End of variables declaration//GEN-END:variables
}
