package GUI.Comp;

import BUS.ExamBUS;
import BUS.ResultBUS;
import DTO.ExamDTO;
import DTO.ResultDTO;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.function.Consumer;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import DTO.TestDTO;
import DTO.UserDTO;
import GUI.Comp.Dialog.DialogDoExam;
import GUI.Comp.Panel.Result.PanelAfterExam;
import GUI.Utils.UserSession;

/**
 * ExamComp class to display exam details.
 * 
 * Author: Minh Phuc
 */
public class ExamComp extends javax.swing.JPanel {
    private TestDTO exam;
    private ExamBUS examBUS = new ExamBUS();
    private ResultBUS resultBUS = new ResultBUS();
    private Consumer<JPanel> showFormCallback;
    private JPanel parent;

    /**
     * Creates new form ExamComp
     */
    public ExamComp(JPanel parent, TestDTO exam) {
        this.parent = parent;
        this.exam = exam;

        initComponents();
        loadExamData(exam);
    }

    public void setShowFormCallback(Consumer<JPanel> handler) {
        showFormCallback = handler;
    }

    private void loadExamData(TestDTO exam) {
        jLabel1.setText("TÊN ĐỀ: ");
        jLabel2.setText("NGÀY GIỜ THI: ");
        jLabel3.setText("THỜI GIAN THI: ");
        jLabel4.setText(exam.getTitle());

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        jLabel5.setText(dateFormat.format(exam.getTestDate()));

        jLabel6.setText(exam.getTestTime() + " phút");
    }

    public String getExamTitle() {
        return exam.getTitle();
    }

    public Date getTestDate() {
        return exam.getTestDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(53, 80, 154));
        jButton2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VÀO THI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel1.setText("TÊN ĐỀ:");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel2.setText("NGÀY GIỜ THI:");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel3.setText("THỜI GIAN THI:");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setText("");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setText("");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4))
                                .addGap(200, 200, 200)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5))
                                .addGap(200, 200, 200)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel3))
                                .addGap(200, 200, 200)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(41, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6)))
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        LocalDate currentDate = LocalDate.now();
        LocalDate examDate = exam.getTestDate().toLocalDate();

        int testLimit = exam.getTestLimit();
        int userTakeExamTime = resultBUS.getTakeExamTime(UserSession.getInstance().getCurrentUser(), exam);

        if (currentDate.isAfter(examDate)) {
            JOptionPane.showMessageDialog(this, "Ngày thi đã qua, bạn không thể vào thi.");
            return;
        }

        if (userTakeExamTime >= testLimit) {
            JOptionPane.showMessageDialog(this, "Bạn đã hết lượt thi!");
            return;
        }

        ExamDTO examDTO = examBUS.randomExamByTestCode(exam.getTestCode());
        DialogDoExam doExam = new DialogDoExam(null, true);
        doExam.setTime(exam.getTestTime());
        doExam.setExCode(examDTO.getExCode());
        doExam.setTitleExam(exam.getTitle(), examDTO.getExCode());
        doExam.setVisible(true);

        toResultView(examDTO);
    }// GEN-LAST:event_jButton2ActionPerformed

    private void toResultView(ExamDTO exam) {
        UserDTO currentUser = UserSession.getInstance().getCurrentUser();

        ResultBUS resultBUS = new ResultBUS();
        ResultDTO result = resultBUS.findByUserAndExam(currentUser, exam);

        var afterExam = new PanelAfterExam(result);
        afterExam.addOnBackToPreviousClickCallback(() -> showFormCallback.accept(parent));
        showFormCallback.accept(afterExam);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}